# Generated by Django 3.2 on 2021-04-07 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210407_0410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='joining_date',
        ),
    ]
